FROM python:3.9

ENV TZ=Asia/Tokyo

ARG project_dir=/app/
ADD . $project_dir
WORKDIR $project_dir

# ライブラリをインストール
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# ポート解放
EXPOSE 8000

CMD ["uvicorn", "start_app:app", "--host", "0.0.0.0", "--reload"]